### ISSUE TITLE
Are there any Posit implementations out there?

### ISSUE THREAD

**Issue by CCurl** [ForthHub/discussion#86]
From what I have read, Posits has many advantages over Floats. 

Does anyone know about any Forth implementations of it?

**Comment by phreda4** [comment]
I don't know about posit but I am almost sure that integers are better than floating point

I only found one case where I couldn't replace them but I think I couldn't find the proper algorithm for this, this is the correct perspective textured triangle drawing.

The easy way to translate the programs is using the fixed point

The approximation of numbers to extend the range of representation does not seem to me a good idea, especially since there will always be a loss of precision, it is preferable to manage these limits of representation

**Comment by CCurl** [comment]
I am not suggesting to replace the integer operations with Posit, but for those cases where you need non-integer numbers, Posit numbers are better in many ways over floating point numbers.

**Comment by phreda4** [comment]
Sorry, I don't think I explain myself well.
I think it is not necessary to use the floating point numbers in any case.

**Comment by CCurl** [comment]
Thanks folks!
